Search.appendIndex(
    [
                {
            "fqsen": "\\Demo",
            "name": "Demo",
            "summary": "",
            "url": "classes/Demo.html"
        },                {
            "fqsen": "\\Demo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Demo.html#method___construct"
        },                {
            "fqsen": "\\Demo\u003A\u003Aloop\u0028\u0029",
            "name": "loop",
            "summary": "",
            "url": "classes/Demo.html#method_loop"
        },                {
            "fqsen": "\\Demo\u003A\u003A\u0024repository",
            "name": "repository",
            "summary": "",
            "url": "classes/Demo.html#property_repository"
        },                {
            "fqsen": "\\Demo\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Demo.html#property_db"
        },                {
            "fqsen": "\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/UserRepository.html"
        },                {
            "fqsen": "\\UserRepository\u003A\u003Ainitialize\u0028\u0029",
            "name": "initialize",
            "summary": "",
            "url": "classes/UserRepository.html#method_initialize"
        },                {
            "fqsen": "\\UserRepository\u003A\u003A\u0024from",
            "name": "from",
            "summary": "",
            "url": "classes/UserRepository.html#property_from"
        },                {
            "fqsen": "\\UserRepository\u003A\u003A\u0024assign",
            "name": "assign",
            "summary": "",
            "url": "classes/UserRepository.html#property_assign"
        },                {
            "fqsen": "\\User",
            "name": "User",
            "summary": "",
            "url": "classes/User.html"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/User.html#property_id"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/User.html#property_name"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024projectName",
            "name": "projectName",
            "summary": "",
            "url": "classes/User.html#property_projectName"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository",
            "name": "AbstractRepository",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method___construct"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Ainitialize\u0028\u0029",
            "name": "initialize",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_initialize"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Acols\u0028\u0029",
            "name": "cols",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_cols"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Awhere\u0028\u0029",
            "name": "where",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_where"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Alike\u0028\u0029",
            "name": "like",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_like"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AwhereIn\u0028\u0029",
            "name": "whereIn",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_whereIn"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AwhereBetween\u0028\u0029",
            "name": "whereBetween",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_whereBetween"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024paging",
            "name": "paging",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_paging"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024with",
            "name": "with",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_with"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AgroupBy\u0028\u0029",
            "name": "groupBy",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_groupBy"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Ahaving\u0028\u0029",
            "name": "having",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_having"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AorderBy\u0028\u0029",
            "name": "orderBy",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_orderBy"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_getIterator"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AfetchOne\u0028\u0029",
            "name": "fetchOne",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_fetchOne"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_count"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AgetPagination\u0028\u0029",
            "name": "getPagination",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_getPagination"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Aassign\u0028\u0029",
            "name": "assign",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_assign"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_clear"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_jsonSerialize"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Ajoin\u0028\u0029",
            "name": "join",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_join"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003Aperform\u0028\u0029",
            "name": "perform",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_perform"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AgetResult\u0028\u0029",
            "name": "getResult",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_getResult"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AbuildQuery\u0028\u0029",
            "name": "buildQuery",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_buildQuery"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AdefaultColumns\u0028\u0029",
            "name": "defaultColumns",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_defaultColumns"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003AgetSelectColumnsFromTable\u0028\u0029",
            "name": "getSelectColumnsFromTable",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#method_getSelectColumnsFromTable"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024from",
            "name": "from",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_from"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024criteria",
            "name": "criteria",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_criteria"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_page"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024pageSize",
            "name": "pageSize",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_pageSize"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024schema",
            "name": "schema",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_schema"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024entity",
            "name": "entity",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_entity"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024conn",
            "name": "conn",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_conn"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\AbstractRepository\u003A\u003A\u0024queryFactory",
            "name": "queryFactory",
            "summary": "",
            "url": "classes/tenjuu99-ORM-AbstractRepository.html#property_queryFactory"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Annotation\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Annotation-Entity.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Annotation\\Entity\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Annotation-Entity.html#method_getName"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Annotation\\Entity\u003A\u003A\u0024prop",
            "name": "prop",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Annotation-Entity.html#property_prop"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Annotation\\Entity\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Annotation-Entity.html#property_table"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria",
            "name": "Criteria",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003A\u0024cols",
            "name": "cols",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#property_cols"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003A\u0024where",
            "name": "where",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#property_where"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003Alike\u0028\u0029",
            "name": "like",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#method_like"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003AwhereIn\u0028\u0029",
            "name": "whereIn",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#method_whereIn"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003AwhereBetween\u0028\u0029",
            "name": "whereBetween",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#method_whereBetween"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003A\u0024join",
            "name": "join",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#property_join"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003A\u0024with",
            "name": "with",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#property_with"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003A\u0024groupBy",
            "name": "groupBy",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#property_groupBy"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003A\u0024having",
            "name": "having",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#property_having"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003A\u0024orderBy",
            "name": "orderBy",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#property_orderBy"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#method_clear"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003Abuild\u0028\u0029",
            "name": "build",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#method_build"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003AsetCondition\u0028\u0029",
            "name": "setCondition",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#method_setCondition"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Criteria\u003A\u003A\u0024condition",
            "name": "condition",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Criteria.html#property_condition"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\DbConnection",
            "name": "DbConnection",
            "summary": "",
            "url": "classes/tenjuu99-ORM-DbConnection.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\DbConnection\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/tenjuu99-ORM-DbConnection.html#method___construct"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\DbConnection\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Queries\u0020the\u0020database\u0020and\u0020returns\u0020a\u0020PDOStatement.",
            "url": "classes/tenjuu99-ORM-DbConnection.html#method_query"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\DbConnection\u003A\u003Aperform\u0028\u0029",
            "name": "perform",
            "summary": "Performs\u0020a\u0020query\u0020after\u0020preparing\u0020the\u0020statement\u0020with\u0020bound\u0020values,\u0020then\nreturns\u0020the\u0020result\u0020as\u0020a\u0020PDOStatement.",
            "url": "classes/tenjuu99-ORM-DbConnection.html#method_perform"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\DbConnection\u003A\u003A\u0024pdo",
            "name": "pdo",
            "summary": "",
            "url": "classes/tenjuu99-ORM-DbConnection.html#property_pdo"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\DbConnectionInterface",
            "name": "DbConnectionInterface",
            "summary": "",
            "url": "classes/tenjuu99-ORM-DbConnectionInterface.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\DbConnectionInterface\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Queries\u0020the\u0020database\u0020and\u0020returns\u0020a\u0020PDOStatement.",
            "url": "classes/tenjuu99-ORM-DbConnectionInterface.html#method_query"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\DbConnectionInterface\u003A\u003Aperform\u0028\u0029",
            "name": "perform",
            "summary": "Performs\u0020a\u0020query\u0020after\u0020preparing\u0020the\u0020statement\u0020with\u0020bound\u0020values,\u0020then\nreturns\u0020the\u0020result\u0020as\u0020a\u0020PDOStatement.",
            "url": "classes/tenjuu99-ORM-DbConnectionInterface.html#method_perform"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\EntityFactory",
            "name": "EntityFactory",
            "summary": "",
            "url": "classes/tenjuu99-ORM-EntityFactory.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\EntityFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/tenjuu99-ORM-EntityFactory.html#method___construct"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\EntityFactory\u003A\u003AsetClass\u0028\u0029",
            "name": "setClass",
            "summary": "",
            "url": "classes/tenjuu99-ORM-EntityFactory.html#method_setClass"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\EntityFactory\u003A\u003Aready\u0028\u0029",
            "name": "ready",
            "summary": "",
            "url": "classes/tenjuu99-ORM-EntityFactory.html#method_ready"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\EntityFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/tenjuu99-ORM-EntityFactory.html#method_create"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\EntityFactory\u003A\u003A\u0024reader",
            "name": "reader",
            "summary": "",
            "url": "classes/tenjuu99-ORM-EntityFactory.html#property_reader"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\EntityFactory\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/tenjuu99-ORM-EntityFactory.html#property_class"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\OrmModule",
            "name": "OrmModule",
            "summary": "",
            "url": "classes/tenjuu99-ORM-OrmModule.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\OrmModule\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/tenjuu99-ORM-OrmModule.html#method___construct"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\OrmModule\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/tenjuu99-ORM-OrmModule.html#method_configure"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\OrmModule\u003A\u003A\u0024dbType",
            "name": "dbType",
            "summary": "",
            "url": "classes/tenjuu99-ORM-OrmModule.html#property_dbType"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination",
            "name": "Pagination",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#method___construct"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003Apages\u0028\u0029",
            "name": "pages",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#method_pages"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003A\u0024count",
            "name": "count",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#property_count"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003A\u0024current",
            "name": "current",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#property_current"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#method_next"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003Aprev\u0028\u0029",
            "name": "prev",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#method_prev"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003Alast\u0028\u0029",
            "name": "last",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#method_last"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003Afirst\u0028\u0029",
            "name": "first",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#method_first"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#method_jsonSerialize"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003AgetUri\u0028\u0029",
            "name": "getUri",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#method_getUri"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#property_uri"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Pagination\u003A\u003A\u0024perPage",
            "name": "perPage",
            "summary": "",
            "url": "classes/tenjuu99-ORM-Pagination.html#property_perPage"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\PdoModule",
            "name": "PdoModule",
            "summary": "",
            "url": "classes/tenjuu99-ORM-PdoModule.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\PdoModule\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/tenjuu99-ORM-PdoModule.html#method___construct"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\PdoModule\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/tenjuu99-ORM-PdoModule.html#method_configure"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\PdoModule\u003A\u003A\u0024dsn",
            "name": "dsn",
            "summary": "",
            "url": "classes/tenjuu99-ORM-PdoModule.html#property_dsn"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\PdoModule\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/tenjuu99-ORM-PdoModule.html#property_username"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\PdoModule\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/tenjuu99-ORM-PdoModule.html#property_password"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\PdoModule\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/tenjuu99-ORM-PdoModule.html#property_options"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema",
            "name": "TableSchema",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#method___construct"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003AgetColumns\u0028\u0029",
            "name": "getColumns",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#method_getColumns"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003AgetAllSchema\u0028\u0029",
            "name": "getAllSchema",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#method_getAllSchema"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003AcolumnsMysql\u0028\u0029",
            "name": "columnsMysql",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#method_columnsMysql"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003AcolumnsSqlite\u0028\u0029",
            "name": "columnsSqlite",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#method_columnsSqlite"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003AQUERY",
            "name": "QUERY",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#constant_QUERY"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003A\u0024conn",
            "name": "conn",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#property_conn"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003A\u0024dbType",
            "name": "dbType",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#property_dbType"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003A\u0024columns",
            "name": "columns",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#property_columns"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\TableSchema\u003A\u003A\u0024allSchema",
            "name": "allSchema",
            "summary": "",
            "url": "classes/tenjuu99-ORM-TableSchema.html#property_allSchema"
        },                {
            "fqsen": "\\tenjuu99\\Test\\DbConnectionTest",
            "name": "DbConnectionTest",
            "summary": "",
            "url": "classes/tenjuu99-Test-DbConnectionTest.html"
        },                {
            "fqsen": "\\tenjuu99\\Test\\DbConnectionTest\u003A\u003AtestQuery\u0028\u0029",
            "name": "testQuery",
            "summary": "",
            "url": "classes/tenjuu99-Test-DbConnectionTest.html#method_testQuery"
        },                {
            "fqsen": "\\tenjuu99\\Test\\DbConnectionTest\u003A\u003AtestPerform\u0028\u0029",
            "name": "testPerform",
            "summary": "",
            "url": "classes/tenjuu99-Test-DbConnectionTest.html#method_testPerform"
        },                {
            "fqsen": "\\tenjuu99\\Test\\RepositoryTest",
            "name": "RepositoryTest",
            "summary": "",
            "url": "classes/tenjuu99-Test-RepositoryTest.html"
        },                {
            "fqsen": "\\tenjuu99\\Test\\RepositoryTest\u003A\u003AsetUpBeforeClass\u0028\u0029",
            "name": "setUpBeforeClass",
            "summary": "",
            "url": "classes/tenjuu99-Test-RepositoryTest.html#method_setUpBeforeClass"
        },                {
            "fqsen": "\\tenjuu99\\Test\\RepositoryTest\u003A\u003AtearDownAfterClass\u0028\u0029",
            "name": "tearDownAfterClass",
            "summary": "",
            "url": "classes/tenjuu99-Test-RepositoryTest.html#method_tearDownAfterClass"
        },                {
            "fqsen": "\\tenjuu99\\Test\\RepositoryTest\u003A\u003AtestRepository\u0028\u0029",
            "name": "testRepository",
            "summary": "",
            "url": "classes/tenjuu99-Test-RepositoryTest.html#method_testRepository"
        },                {
            "fqsen": "\\tenjuu99\\Test\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/tenjuu99-Test-UserRepository.html"
        },                {
            "fqsen": "\\tenjuu99\\Test\\UserRepository\u003A\u003A\u0024from",
            "name": "from",
            "summary": "",
            "url": "classes/tenjuu99-Test-UserRepository.html#property_from"
        },                {
            "fqsen": "\\tenjuu99\\Test\\User",
            "name": "User",
            "summary": "",
            "url": "classes/tenjuu99-Test-User.html"
        },                {
            "fqsen": "\\tenjuu99\\Test\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/tenjuu99-Test-User.html#property_id"
        },                {
            "fqsen": "\\tenjuu99\\Test\\User\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/tenjuu99-Test-User.html#property_name"
        },                {
            "fqsen": "\\tenjuu99\\Test\\TableSchemaTest",
            "name": "TableSchemaTest",
            "summary": "",
            "url": "classes/tenjuu99-Test-TableSchemaTest.html"
        },                {
            "fqsen": "\\tenjuu99\\Test\\TableSchemaTest\u003A\u003AsetUpBeforeClass\u0028\u0029",
            "name": "setUpBeforeClass",
            "summary": "",
            "url": "classes/tenjuu99-Test-TableSchemaTest.html#method_setUpBeforeClass"
        },                {
            "fqsen": "\\tenjuu99\\Test\\TableSchemaTest\u003A\u003AtearDownAfterClass\u0028\u0029",
            "name": "tearDownAfterClass",
            "summary": "",
            "url": "classes/tenjuu99-Test-TableSchemaTest.html#method_tearDownAfterClass"
        },                {
            "fqsen": "\\tenjuu99\\Test\\TableSchemaTest\u003A\u003AtestGetColumns\u0028\u0029",
            "name": "testGetColumns",
            "summary": "",
            "url": "classes/tenjuu99-Test-TableSchemaTest.html#method_testGetColumns"
        },                {
            "fqsen": "\\tenjuu99\\Test\\TableSchemaTest\u003A\u003A\u0024conn",
            "name": "conn",
            "summary": "",
            "url": "classes/tenjuu99-Test-TableSchemaTest.html#property_conn"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM",
            "name": "ORM",
            "summary": "",
            "url": "namespaces/tenjuu99-orm.html"
        },                {
            "fqsen": "\\tenjuu99",
            "name": "tenjuu99",
            "summary": "",
            "url": "namespaces/tenjuu99.html"
        },                {
            "fqsen": "\\tenjuu99\\ORM\\Annotation",
            "name": "Annotation",
            "summary": "",
            "url": "namespaces/tenjuu99-orm-annotation.html"
        },                {
            "fqsen": "\\tenjuu99\\Test",
            "name": "Test",
            "summary": "",
            "url": "namespaces/tenjuu99-test.html"
        }            ]
);
